### PR TITLE
Updated views,forms, html.

### PR DESCRIPTION
**Pull request by pault2k14**

### CODE REVIEW

**Comment by mdj2** [comment]
Now I understand what you did. Never just copy and paste in changes like that. It makes merging harder.

Tomorrow when you come in, I'll show you how to fix this.

**Comment by pault2k14** [comment]
Hey Matt,

I didn't copy and paste any thing. I looked at the changes you made, then
made those changes in the settings.py, and Makefile. Maybe i missed one of
the changes?

Ok well lets talk about it tomorrow.

Thanks,
Paul

**Comment by mdj2** [comment]
> I didn't copy and paste any thing. I looked at the changes you made, then made those changes in the settings.py, and Makefile.

Well, that's even worse! Copying and pasting would have been more efficient ;)

Either way, you should be using git to integrate upstream changes. Don't just copy them into your project by hand. Otherwise, you have to ask questions like this:

> Maybe i missed one of the changes?

**Comment by pault2k14** [comment]
Hey Matt,

I see the part that I messed up on, with the Makefile.

Thanks,
Paul.

**Comment by pault2k14** [comment]
Hey Matt,

Your definitely right about that.

Thanks,
Paul

**Pull request closed without merging**
